/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDokumenRouteImport } from './routes/admin/dokumen'
import { Route as AdminDokumenLaporanRouteImport } from './routes/admin/dokumen-laporan'
import { Route as AdminKategoriDipRouteImport } from './routes/admin/kategori-dip'
import { Route as AdminLayananInformasiRouteImport } from './routes/admin/layanan-informasi'
import { Route as AdminStandarLayananRouteImport } from './routes/admin/standar-layanan'
import { Route as InformasiPublikDipRouteImport } from './routes/informasi-publik/dip'
import { Route as InformasiPublikDokumenLaporanRouteImport } from './routes/informasi-publik/dokumen-laporan'
import { Route as LayananInformasiKeberatanRouteImport } from './routes/layanan-informasi/keberatan'
import { Route as LayananInformasiLacakRouteImport } from './routes/layanan-informasi/lacak'
import { Route as LayananInformasiPermohonanRouteImport } from './routes/layanan-informasi/permohonan'
import { Route as LayananInformasiSaluranInformasiRouteImport } from './routes/layanan-informasi/saluran-informasi'
import { Route as LayananInformasiStandarPengumumanRouteImport } from './routes/layanan-informasi/standar-pengumuman'
import { Route as LayananInformasiTataCaraRouteImport } from './routes/layanan-informasi/tata-cara'
import { Route as ProfilKantorKemenagKubarRouteImport } from './routes/profil/kantor-kemenag-kubar'
import { Route as ProfilPpidRouteImport } from './routes/profil/ppid'
import { Route as RegulasiIndexRouteImport } from './routes/regulasi/index'
import { Route as StandarLayananKebijakanRouteImport } from './routes/standar-layanan/kebijakan'
import { Route as StandarLayananMaklumatPelayananRouteImport } from './routes/standar-layanan/maklumat-pelayanan'
import { Route as StandarLayananSopRouteImport } from './routes/standar-layanan/sop'
import { Route as InformasiPublikCategorySlugRouteImport } from './routes/informasi-publik/$category/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDokumenRoute = AdminDokumenRouteImport.update({
  id: '/admin/dokumen',
  path: '/admin/dokumen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDokumenLaporanRoute = AdminDokumenLaporanRouteImport.update({
  id: '/admin/dokumen-laporan',
  path: '/admin/dokumen-laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKategoriDipRoute = AdminKategoriDipRouteImport.update({
  id: '/admin/kategori-dip',
  path: '/admin/kategori-dip',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayananInformasiRoute = AdminLayananInformasiRouteImport.update({
  id: '/admin/layanan-informasi',
  path: '/admin/layanan-informasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStandarLayananRoute = AdminStandarLayananRouteImport.update({
  id: '/admin/standar-layanan',
  path: '/admin/standar-layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPublikDipRoute = InformasiPublikDipRouteImport.update({
  id: '/informasi-publik/dip',
  path: '/informasi-publik/dip',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPublikDokumenLaporanRoute =
  InformasiPublikDokumenLaporanRouteImport.update({
    id: '/informasi-publik/dokumen-laporan',
    path: '/informasi-publik/dokumen-laporan',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayananInformasiKeberatanRoute =
  LayananInformasiKeberatanRouteImport.update({
    id: '/layanan-informasi/keberatan',
    path: '/layanan-informasi/keberatan',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayananInformasiLacakRoute = LayananInformasiLacakRouteImport.update({
  id: '/layanan-informasi/lacak',
  path: '/layanan-informasi/lacak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananInformasiPermohonanRoute =
  LayananInformasiPermohonanRouteImport.update({
    id: '/layanan-informasi/permohonan',
    path: '/layanan-informasi/permohonan',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayananInformasiSaluranInformasiRoute =
  LayananInformasiSaluranInformasiRouteImport.update({
    id: '/layanan-informasi/saluran-informasi',
    path: '/layanan-informasi/saluran-informasi',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayananInformasiStandarPengumumanRoute =
  LayananInformasiStandarPengumumanRouteImport.update({
    id: '/layanan-informasi/standar-pengumuman',
    path: '/layanan-informasi/standar-pengumuman',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayananInformasiTataCaraRoute =
  LayananInformasiTataCaraRouteImport.update({
    id: '/layanan-informasi/tata-cara',
    path: '/layanan-informasi/tata-cara',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilKantorKemenagKubarRoute =
  ProfilKantorKemenagKubarRouteImport.update({
    id: '/profil/kantor-kemenag-kubar',
    path: '/profil/kantor-kemenag-kubar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilPpidRoute = ProfilPpidRouteImport.update({
  id: '/profil/ppid',
  path: '/profil/ppid',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulasiIndexRoute = RegulasiIndexRouteImport.update({
  id: '/regulasi/',
  path: '/regulasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandarLayananKebijakanRoute = StandarLayananKebijakanRouteImport.update({
  id: '/standar-layanan/kebijakan',
  path: '/standar-layanan/kebijakan',
  getParentRoute: () => rootRouteImport,
} as any)
const StandarLayananMaklumatPelayananRoute =
  StandarLayananMaklumatPelayananRouteImport.update({
    id: '/standar-layanan/maklumat-pelayanan',
    path: '/standar-layanan/maklumat-pelayanan',
    getParentRoute: () => rootRouteImport,
  } as any)
const StandarLayananSopRoute = StandarLayananSopRouteImport.update({
  id: '/standar-layanan/sop',
  path: '/standar-layanan/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPublikCategorySlugRoute =
  InformasiPublikCategorySlugRouteImport.update({
    id: '/informasi-publik/$category/$slug',
    path: '/informasi-publik/$category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/dokumen-laporan': typeof AdminDokumenLaporanRoute
  '/admin/kategori-dip': typeof AdminKategoriDipRoute
  '/admin/layanan-informasi': typeof AdminLayananInformasiRoute
  '/admin/standar-layanan': typeof AdminStandarLayananRoute
  '/informasi-publik/dip': typeof InformasiPublikDipRoute
  '/informasi-publik/dokumen-laporan': typeof InformasiPublikDokumenLaporanRoute
  '/layanan-informasi/keberatan': typeof LayananInformasiKeberatanRoute
  '/layanan-informasi/lacak': typeof LayananInformasiLacakRoute
  '/layanan-informasi/permohonan': typeof LayananInformasiPermohonanRoute
  '/layanan-informasi/saluran-informasi': typeof LayananInformasiSaluranInformasiRoute
  '/layanan-informasi/standar-pengumuman': typeof LayananInformasiStandarPengumumanRoute
  '/layanan-informasi/tata-cara': typeof LayananInformasiTataCaraRoute
  '/profil/kantor-kemenag-kubar': typeof ProfilKantorKemenagKubarRoute
  '/profil/ppid': typeof ProfilPpidRoute
  '/standar-layanan/kebijakan': typeof StandarLayananKebijakanRoute
  '/standar-layanan/maklumat-pelayanan': typeof StandarLayananMaklumatPelayananRoute
  '/standar-layanan/sop': typeof StandarLayananSopRoute
  '/admin/': typeof AdminIndexRoute
  '/regulasi/': typeof RegulasiIndexRoute
  '/informasi-publik/$category/$slug': typeof InformasiPublikCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/dokumen-laporan': typeof AdminDokumenLaporanRoute
  '/admin/kategori-dip': typeof AdminKategoriDipRoute
  '/admin/layanan-informasi': typeof AdminLayananInformasiRoute
  '/admin/standar-layanan': typeof AdminStandarLayananRoute
  '/informasi-publik/dip': typeof InformasiPublikDipRoute
  '/informasi-publik/dokumen-laporan': typeof InformasiPublikDokumenLaporanRoute
  '/layanan-informasi/keberatan': typeof LayananInformasiKeberatanRoute
  '/layanan-informasi/lacak': typeof LayananInformasiLacakRoute
  '/layanan-informasi/permohonan': typeof LayananInformasiPermohonanRoute
  '/layanan-informasi/saluran-informasi': typeof LayananInformasiSaluranInformasiRoute
  '/layanan-informasi/standar-pengumuman': typeof LayananInformasiStandarPengumumanRoute
  '/layanan-informasi/tata-cara': typeof LayananInformasiTataCaraRoute
  '/profil/kantor-kemenag-kubar': typeof ProfilKantorKemenagKubarRoute
  '/profil/ppid': typeof ProfilPpidRoute
  '/standar-layanan/kebijakan': typeof StandarLayananKebijakanRoute
  '/standar-layanan/maklumat-pelayanan': typeof StandarLayananMaklumatPelayananRoute
  '/standar-layanan/sop': typeof StandarLayananSopRoute
  '/admin': typeof AdminIndexRoute
  '/regulasi': typeof RegulasiIndexRoute
  '/informasi-publik/$category/$slug': typeof InformasiPublikCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/dokumen-laporan': typeof AdminDokumenLaporanRoute
  '/admin/kategori-dip': typeof AdminKategoriDipRoute
  '/admin/layanan-informasi': typeof AdminLayananInformasiRoute
  '/admin/standar-layanan': typeof AdminStandarLayananRoute
  '/informasi-publik/dip': typeof InformasiPublikDipRoute
  '/informasi-publik/dokumen-laporan': typeof InformasiPublikDokumenLaporanRoute
  '/layanan-informasi/keberatan': typeof LayananInformasiKeberatanRoute
  '/layanan-informasi/lacak': typeof LayananInformasiLacakRoute
  '/layanan-informasi/permohonan': typeof LayananInformasiPermohonanRoute
  '/layanan-informasi/saluran-informasi': typeof LayananInformasiSaluranInformasiRoute
  '/layanan-informasi/standar-pengumuman': typeof LayananInformasiStandarPengumumanRoute
  '/layanan-informasi/tata-cara': typeof LayananInformasiTataCaraRoute
  '/profil/kantor-kemenag-kubar': typeof ProfilKantorKemenagKubarRoute
  '/profil/ppid': typeof ProfilPpidRoute
  '/standar-layanan/kebijakan': typeof StandarLayananKebijakanRoute
  '/standar-layanan/maklumat-pelayanan': typeof StandarLayananMaklumatPelayananRoute
  '/standar-layanan/sop': typeof StandarLayananSopRoute
  '/admin/': typeof AdminIndexRoute
  '/regulasi/': typeof RegulasiIndexRoute
  '/informasi-publik/$category/$slug': typeof InformasiPublikCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/masuk'
    | '/admin/dokumen'
    | '/admin/dokumen-laporan'
    | '/admin/kategori-dip'
    | '/admin/layanan-informasi'
    | '/admin/standar-layanan'
    | '/informasi-publik/dip'
    | '/informasi-publik/dokumen-laporan'
    | '/layanan-informasi/keberatan'
    | '/layanan-informasi/lacak'
    | '/layanan-informasi/permohonan'
    | '/layanan-informasi/saluran-informasi'
    | '/layanan-informasi/standar-pengumuman'
    | '/layanan-informasi/tata-cara'
    | '/profil/kantor-kemenag-kubar'
    | '/profil/ppid'
    | '/standar-layanan/kebijakan'
    | '/standar-layanan/maklumat-pelayanan'
    | '/standar-layanan/sop'
    | '/admin/'
    | '/regulasi/'
    | '/informasi-publik/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/masuk'
    | '/admin/dokumen'
    | '/admin/dokumen-laporan'
    | '/admin/kategori-dip'
    | '/admin/layanan-informasi'
    | '/admin/standar-layanan'
    | '/informasi-publik/dip'
    | '/informasi-publik/dokumen-laporan'
    | '/layanan-informasi/keberatan'
    | '/layanan-informasi/lacak'
    | '/layanan-informasi/permohonan'
    | '/layanan-informasi/saluran-informasi'
    | '/layanan-informasi/standar-pengumuman'
    | '/layanan-informasi/tata-cara'
    | '/profil/kantor-kemenag-kubar'
    | '/profil/ppid'
    | '/standar-layanan/kebijakan'
    | '/standar-layanan/maklumat-pelayanan'
    | '/standar-layanan/sop'
    | '/admin'
    | '/regulasi'
    | '/informasi-publik/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/masuk'
    | '/admin/dokumen'
    | '/admin/dokumen-laporan'
    | '/admin/kategori-dip'
    | '/admin/layanan-informasi'
    | '/admin/standar-layanan'
    | '/informasi-publik/dip'
    | '/informasi-publik/dokumen-laporan'
    | '/layanan-informasi/keberatan'
    | '/layanan-informasi/lacak'
    | '/layanan-informasi/permohonan'
    | '/layanan-informasi/saluran-informasi'
    | '/layanan-informasi/standar-pengumuman'
    | '/layanan-informasi/tata-cara'
    | '/profil/kantor-kemenag-kubar'
    | '/profil/ppid'
    | '/standar-layanan/kebijakan'
    | '/standar-layanan/maklumat-pelayanan'
    | '/standar-layanan/sop'
    | '/admin/'
    | '/regulasi/'
    | '/informasi-publik/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasukRoute: typeof MasukRoute
  AdminDokumenRoute: typeof AdminDokumenRoute
  AdminDokumenLaporanRoute: typeof AdminDokumenLaporanRoute
  AdminKategoriDipRoute: typeof AdminKategoriDipRoute
  AdminLayananInformasiRoute: typeof AdminLayananInformasiRoute
  AdminStandarLayananRoute: typeof AdminStandarLayananRoute
  InformasiPublikDipRoute: typeof InformasiPublikDipRoute
  InformasiPublikDokumenLaporanRoute: typeof InformasiPublikDokumenLaporanRoute
  LayananInformasiKeberatanRoute: typeof LayananInformasiKeberatanRoute
  LayananInformasiLacakRoute: typeof LayananInformasiLacakRoute
  LayananInformasiPermohonanRoute: typeof LayananInformasiPermohonanRoute
  LayananInformasiSaluranInformasiRoute: typeof LayananInformasiSaluranInformasiRoute
  LayananInformasiStandarPengumumanRoute: typeof LayananInformasiStandarPengumumanRoute
  LayananInformasiTataCaraRoute: typeof LayananInformasiTataCaraRoute
  ProfilKantorKemenagKubarRoute: typeof ProfilKantorKemenagKubarRoute
  ProfilPpidRoute: typeof ProfilPpidRoute
  StandarLayananKebijakanRoute: typeof StandarLayananKebijakanRoute
  StandarLayananMaklumatPelayananRoute: typeof StandarLayananMaklumatPelayananRoute
  StandarLayananSopRoute: typeof StandarLayananSopRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RegulasiIndexRoute: typeof RegulasiIndexRoute
  InformasiPublikCategorySlugRoute: typeof InformasiPublikCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dokumen': {
      id: '/admin/dokumen'
      path: '/admin/dokumen'
      fullPath: '/admin/dokumen'
      preLoaderRoute: typeof AdminDokumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dokumen-laporan': {
      id: '/admin/dokumen-laporan'
      path: '/admin/dokumen-laporan'
      fullPath: '/admin/dokumen-laporan'
      preLoaderRoute: typeof AdminDokumenLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kategori-dip': {
      id: '/admin/kategori-dip'
      path: '/admin/kategori-dip'
      fullPath: '/admin/kategori-dip'
      preLoaderRoute: typeof AdminKategoriDipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/layanan-informasi': {
      id: '/admin/layanan-informasi'
      path: '/admin/layanan-informasi'
      fullPath: '/admin/layanan-informasi'
      preLoaderRoute: typeof AdminLayananInformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/standar-layanan': {
      id: '/admin/standar-layanan'
      path: '/admin/standar-layanan'
      fullPath: '/admin/standar-layanan'
      preLoaderRoute: typeof AdminStandarLayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-publik/dip': {
      id: '/informasi-publik/dip'
      path: '/informasi-publik/dip'
      fullPath: '/informasi-publik/dip'
      preLoaderRoute: typeof InformasiPublikDipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-publik/dokumen-laporan': {
      id: '/informasi-publik/dokumen-laporan'
      path: '/informasi-publik/dokumen-laporan'
      fullPath: '/informasi-publik/dokumen-laporan'
      preLoaderRoute: typeof InformasiPublikDokumenLaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/keberatan': {
      id: '/layanan-informasi/keberatan'
      path: '/layanan-informasi/keberatan'
      fullPath: '/layanan-informasi/keberatan'
      preLoaderRoute: typeof LayananInformasiKeberatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/lacak': {
      id: '/layanan-informasi/lacak'
      path: '/layanan-informasi/lacak'
      fullPath: '/layanan-informasi/lacak'
      preLoaderRoute: typeof LayananInformasiLacakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/permohonan': {
      id: '/layanan-informasi/permohonan'
      path: '/layanan-informasi/permohonan'
      fullPath: '/layanan-informasi/permohonan'
      preLoaderRoute: typeof LayananInformasiPermohonanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/saluran-informasi': {
      id: '/layanan-informasi/saluran-informasi'
      path: '/layanan-informasi/saluran-informasi'
      fullPath: '/layanan-informasi/saluran-informasi'
      preLoaderRoute: typeof LayananInformasiSaluranInformasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/standar-pengumuman': {
      id: '/layanan-informasi/standar-pengumuman'
      path: '/layanan-informasi/standar-pengumuman'
      fullPath: '/layanan-informasi/standar-pengumuman'
      preLoaderRoute: typeof LayananInformasiStandarPengumumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/tata-cara': {
      id: '/layanan-informasi/tata-cara'
      path: '/layanan-informasi/tata-cara'
      fullPath: '/layanan-informasi/tata-cara'
      preLoaderRoute: typeof LayananInformasiTataCaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/kantor-kemenag-kubar': {
      id: '/profil/kantor-kemenag-kubar'
      path: '/profil/kantor-kemenag-kubar'
      fullPath: '/profil/kantor-kemenag-kubar'
      preLoaderRoute: typeof ProfilKantorKemenagKubarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/ppid': {
      id: '/profil/ppid'
      path: '/profil/ppid'
      fullPath: '/profil/ppid'
      preLoaderRoute: typeof ProfilPpidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulasi/': {
      id: '/regulasi/'
      path: '/regulasi'
      fullPath: '/regulasi/'
      preLoaderRoute: typeof RegulasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standar-layanan/kebijakan': {
      id: '/standar-layanan/kebijakan'
      path: '/standar-layanan/kebijakan'
      fullPath: '/standar-layanan/kebijakan'
      preLoaderRoute: typeof StandarLayananKebijakanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standar-layanan/maklumat-pelayanan': {
      id: '/standar-layanan/maklumat-pelayanan'
      path: '/standar-layanan/maklumat-pelayanan'
      fullPath: '/standar-layanan/maklumat-pelayanan'
      preLoaderRoute: typeof StandarLayananMaklumatPelayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standar-layanan/sop': {
      id: '/standar-layanan/sop'
      path: '/standar-layanan/sop'
      fullPath: '/standar-layanan/sop'
      preLoaderRoute: typeof StandarLayananSopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-publik/$category/$slug': {
      id: '/informasi-publik/$category/$slug'
      path: '/informasi-publik/$category/$slug'
      fullPath: '/informasi-publik/$category/$slug'
      preLoaderRoute: typeof InformasiPublikCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasukRoute: MasukRoute,
  AdminDokumenRoute: AdminDokumenRoute,
  AdminDokumenLaporanRoute: AdminDokumenLaporanRoute,
  AdminKategoriDipRoute: AdminKategoriDipRoute,
  AdminLayananInformasiRoute: AdminLayananInformasiRoute,
  AdminStandarLayananRoute: AdminStandarLayananRoute,
  InformasiPublikDipRoute: InformasiPublikDipRoute,
  InformasiPublikDokumenLaporanRoute: InformasiPublikDokumenLaporanRoute,
  LayananInformasiKeberatanRoute: LayananInformasiKeberatanRoute,
  LayananInformasiLacakRoute: LayananInformasiLacakRoute,
  LayananInformasiPermohonanRoute: LayananInformasiPermohonanRoute,
  LayananInformasiSaluranInformasiRoute: LayananInformasiSaluranInformasiRoute,
  LayananInformasiStandarPengumumanRoute:
    LayananInformasiStandarPengumumanRoute,
  LayananInformasiTataCaraRoute: LayananInformasiTataCaraRoute,
  ProfilKantorKemenagKubarRoute: ProfilKantorKemenagKubarRoute,
  ProfilPpidRoute: ProfilPpidRoute,
  StandarLayananKebijakanRoute: StandarLayananKebijakanRoute,
  StandarLayananMaklumatPelayananRoute: StandarLayananMaklumatPelayananRoute,
  StandarLayananSopRoute: StandarLayananSopRoute,
  AdminIndexRoute: AdminIndexRoute,
  RegulasiIndexRoute: RegulasiIndexRoute,
  InformasiPublikCategorySlugRoute: InformasiPublikCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
