/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDokumenRouteImport } from './routes/admin/dokumen'
import { Route as AdminKategoriDipRouteImport } from './routes/admin/kategori-dip'
import { Route as InformasiPublikIndexRouteImport } from './routes/informasi-publik/index'
import { Route as InformasiPublikDipRouteImport } from './routes/informasi-publik/dip'
import { Route as LayananInformasiIndexRouteImport } from './routes/layanan-informasi/index'
import { Route as LayananInformasiKeberatanRouteImport } from './routes/layanan-informasi/keberatan'
import { Route as LayananInformasiLacakRouteImport } from './routes/layanan-informasi/lacak'
import { Route as LayananInformasiPermohonanRouteImport } from './routes/layanan-informasi/permohonan'
import { Route as ProfilIndexRouteImport } from './routes/profil/index'
import { Route as RegulasiIndexRouteImport } from './routes/regulasi/index'
import { Route as StandarLayananIndexRouteImport } from './routes/standar-layanan/index'
import { Route as InformasiPublikCategorySlugRouteImport } from './routes/informasi-publik/$category/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDokumenRoute = AdminDokumenRouteImport.update({
  id: '/admin/dokumen',
  path: '/admin/dokumen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKategoriDipRoute = AdminKategoriDipRouteImport.update({
  id: '/admin/kategori-dip',
  path: '/admin/kategori-dip',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPublikIndexRoute = InformasiPublikIndexRouteImport.update({
  id: '/informasi-publik/',
  path: '/informasi-publik/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPublikDipRoute = InformasiPublikDipRouteImport.update({
  id: '/informasi-publik/dip',
  path: '/informasi-publik/dip',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananInformasiIndexRoute = LayananInformasiIndexRouteImport.update({
  id: '/layanan-informasi/',
  path: '/layanan-informasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananInformasiKeberatanRoute =
  LayananInformasiKeberatanRouteImport.update({
    id: '/layanan-informasi/keberatan',
    path: '/layanan-informasi/keberatan',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayananInformasiLacakRoute = LayananInformasiLacakRouteImport.update({
  id: '/layanan-informasi/lacak',
  path: '/layanan-informasi/lacak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananInformasiPermohonanRoute =
  LayananInformasiPermohonanRouteImport.update({
    id: '/layanan-informasi/permohonan',
    path: '/layanan-informasi/permohonan',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/profil/',
  path: '/profil/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulasiIndexRoute = RegulasiIndexRouteImport.update({
  id: '/regulasi/',
  path: '/regulasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandarLayananIndexRoute = StandarLayananIndexRouteImport.update({
  id: '/standar-layanan/',
  path: '/standar-layanan/',
  getParentRoute: () => rootRouteImport,
} as any)
const InformasiPublikCategorySlugRoute =
  InformasiPublikCategorySlugRouteImport.update({
    id: '/informasi-publik/$category/$slug',
    path: '/informasi-publik/$category/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/kategori-dip': typeof AdminKategoriDipRoute
  '/informasi-publik/dip': typeof InformasiPublikDipRoute
  '/layanan-informasi/keberatan': typeof LayananInformasiKeberatanRoute
  '/layanan-informasi/lacak': typeof LayananInformasiLacakRoute
  '/layanan-informasi/permohonan': typeof LayananInformasiPermohonanRoute
  '/admin/': typeof AdminIndexRoute
  '/informasi-publik/': typeof InformasiPublikIndexRoute
  '/layanan-informasi/': typeof LayananInformasiIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/regulasi/': typeof RegulasiIndexRoute
  '/standar-layanan/': typeof StandarLayananIndexRoute
  '/informasi-publik/$category/$slug': typeof InformasiPublikCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/kategori-dip': typeof AdminKategoriDipRoute
  '/informasi-publik/dip': typeof InformasiPublikDipRoute
  '/layanan-informasi/keberatan': typeof LayananInformasiKeberatanRoute
  '/layanan-informasi/lacak': typeof LayananInformasiLacakRoute
  '/layanan-informasi/permohonan': typeof LayananInformasiPermohonanRoute
  '/admin': typeof AdminIndexRoute
  '/informasi-publik': typeof InformasiPublikIndexRoute
  '/layanan-informasi': typeof LayananInformasiIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/regulasi': typeof RegulasiIndexRoute
  '/standar-layanan': typeof StandarLayananIndexRoute
  '/informasi-publik/$category/$slug': typeof InformasiPublikCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/kategori-dip': typeof AdminKategoriDipRoute
  '/informasi-publik/dip': typeof InformasiPublikDipRoute
  '/layanan-informasi/keberatan': typeof LayananInformasiKeberatanRoute
  '/layanan-informasi/lacak': typeof LayananInformasiLacakRoute
  '/layanan-informasi/permohonan': typeof LayananInformasiPermohonanRoute
  '/admin/': typeof AdminIndexRoute
  '/informasi-publik/': typeof InformasiPublikIndexRoute
  '/layanan-informasi/': typeof LayananInformasiIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/regulasi/': typeof RegulasiIndexRoute
  '/standar-layanan/': typeof StandarLayananIndexRoute
  '/informasi-publik/$category/$slug': typeof InformasiPublikCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/masuk'
    | '/admin/dokumen'
    | '/admin/kategori-dip'
    | '/informasi-publik/dip'
    | '/layanan-informasi/keberatan'
    | '/layanan-informasi/lacak'
    | '/layanan-informasi/permohonan'
    | '/admin/'
    | '/informasi-publik/'
    | '/layanan-informasi/'
    | '/profil/'
    | '/regulasi/'
    | '/standar-layanan/'
    | '/informasi-publik/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/masuk'
    | '/admin/dokumen'
    | '/admin/kategori-dip'
    | '/informasi-publik/dip'
    | '/layanan-informasi/keberatan'
    | '/layanan-informasi/lacak'
    | '/layanan-informasi/permohonan'
    | '/admin'
    | '/informasi-publik'
    | '/layanan-informasi'
    | '/profil'
    | '/regulasi'
    | '/standar-layanan'
    | '/informasi-publik/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/masuk'
    | '/admin/dokumen'
    | '/admin/kategori-dip'
    | '/informasi-publik/dip'
    | '/layanan-informasi/keberatan'
    | '/layanan-informasi/lacak'
    | '/layanan-informasi/permohonan'
    | '/admin/'
    | '/informasi-publik/'
    | '/layanan-informasi/'
    | '/profil/'
    | '/regulasi/'
    | '/standar-layanan/'
    | '/informasi-publik/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MasukRoute: typeof MasukRoute
  AdminDokumenRoute: typeof AdminDokumenRoute
  AdminKategoriDipRoute: typeof AdminKategoriDipRoute
  InformasiPublikDipRoute: typeof InformasiPublikDipRoute
  LayananInformasiKeberatanRoute: typeof LayananInformasiKeberatanRoute
  LayananInformasiLacakRoute: typeof LayananInformasiLacakRoute
  LayananInformasiPermohonanRoute: typeof LayananInformasiPermohonanRoute
  AdminIndexRoute: typeof AdminIndexRoute
  InformasiPublikIndexRoute: typeof InformasiPublikIndexRoute
  LayananInformasiIndexRoute: typeof LayananInformasiIndexRoute
  ProfilIndexRoute: typeof ProfilIndexRoute
  RegulasiIndexRoute: typeof RegulasiIndexRoute
  StandarLayananIndexRoute: typeof StandarLayananIndexRoute
  InformasiPublikCategorySlugRoute: typeof InformasiPublikCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dokumen': {
      id: '/admin/dokumen'
      path: '/admin/dokumen'
      fullPath: '/admin/dokumen'
      preLoaderRoute: typeof AdminDokumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kategori-dip': {
      id: '/admin/kategori-dip'
      path: '/admin/kategori-dip'
      fullPath: '/admin/kategori-dip'
      preLoaderRoute: typeof AdminKategoriDipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-publik/': {
      id: '/informasi-publik/'
      path: '/informasi-publik'
      fullPath: '/informasi-publik/'
      preLoaderRoute: typeof InformasiPublikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-publik/dip': {
      id: '/informasi-publik/dip'
      path: '/informasi-publik/dip'
      fullPath: '/informasi-publik/dip'
      preLoaderRoute: typeof InformasiPublikDipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/': {
      id: '/layanan-informasi/'
      path: '/layanan-informasi'
      fullPath: '/layanan-informasi/'
      preLoaderRoute: typeof LayananInformasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/keberatan': {
      id: '/layanan-informasi/keberatan'
      path: '/layanan-informasi/keberatan'
      fullPath: '/layanan-informasi/keberatan'
      preLoaderRoute: typeof LayananInformasiKeberatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/lacak': {
      id: '/layanan-informasi/lacak'
      path: '/layanan-informasi/lacak'
      fullPath: '/layanan-informasi/lacak'
      preLoaderRoute: typeof LayananInformasiLacakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan-informasi/permohonan': {
      id: '/layanan-informasi/permohonan'
      path: '/layanan-informasi/permohonan'
      fullPath: '/layanan-informasi/permohonan'
      preLoaderRoute: typeof LayananInformasiPermohonanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/profil'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulasi/': {
      id: '/regulasi/'
      path: '/regulasi'
      fullPath: '/regulasi/'
      preLoaderRoute: typeof RegulasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standar-layanan/': {
      id: '/standar-layanan/'
      path: '/standar-layanan'
      fullPath: '/standar-layanan/'
      preLoaderRoute: typeof StandarLayananIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informasi-publik/$category/$slug': {
      id: '/informasi-publik/$category/$slug'
      path: '/informasi-publik/$category/$slug'
      fullPath: '/informasi-publik/$category/$slug'
      preLoaderRoute: typeof InformasiPublikCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MasukRoute: MasukRoute,
  AdminDokumenRoute: AdminDokumenRoute,
  AdminKategoriDipRoute: AdminKategoriDipRoute,
  InformasiPublikDipRoute: InformasiPublikDipRoute,
  LayananInformasiKeberatanRoute: LayananInformasiKeberatanRoute,
  LayananInformasiLacakRoute: LayananInformasiLacakRoute,
  LayananInformasiPermohonanRoute: LayananInformasiPermohonanRoute,
  AdminIndexRoute: AdminIndexRoute,
  InformasiPublikIndexRoute: InformasiPublikIndexRoute,
  LayananInformasiIndexRoute: LayananInformasiIndexRoute,
  ProfilIndexRoute: ProfilIndexRoute,
  RegulasiIndexRoute: RegulasiIndexRoute,
  StandarLayananIndexRoute: StandarLayananIndexRoute,
  InformasiPublikCategorySlugRoute: InformasiPublikCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
